name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Build frontend and generate output
        run: sh ./build.sh
      - name: Pushes to personal repo for Vercel deploy
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_DEPLOY_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: yuminnnnni
          destination-repository-name: comket-monorepo
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.head_commit.message }}
          target-branch: main

      - name: Confirm result
        run: echo "Output has been pushed to the personal repo"
